### ISSUE TITLE
Hi Skinz 

### ISSUE THREAD

**Issue by efsanevidemir** [Skinz3/Skinz3#1]
Hello Skinz, I was lovingly using the bot you made for League of Legends. I had to reset my computer and unfortunately it was deleted. I saw that it was removed from GitHub. I have a request from you, please install the bot again on Github or anywhere pls <3

**Comment by Skinz3** [comment]
Hello !
Sorry, but I realized that I was uncomfortable with distributing software publicly that violates the riot games term of use.

**Comment by efsanevidemir** [comment]
Well can't you send me a private message? It worked really well
